# Config file for VoteReward by LDX.
#
# Official VoteReward Server List Directory:
# http://votereward.mcpe.me/?p=lists
#
# Config Variables:
#   {USERNAME} ... The username of the player who voted. ....... Commands and message.
#   {NICKNAME} ... The display name of the player who voted. ... Commands and message.
#   {X} .......... The X coordinate of the player. ............. Commands only.
#   {Y} .......... The Y coordinate of the player. ............. Commands only.
#   {Y1} ......... The Y coordinate of the player plus 1. ...... Commands only.
#   {Z} .......... The Z coordinate of the player. ............. Commands only.

# EssentialsPE style color codes can be used in the message and commands.

# Message to broadcast to the server when a player votes.
Message: "§l§b[§a §l§eᴍɪɴᴇ§bᴛᴏᴡɴ §b]§6 Chúc mừng bạn §e{NICKNAME}§6 vừa vote nhận được:§a 15 Mcoin, 20 RbCoin, 200K VNĐ, 1 KEY VOTE và 1 KEY PREMIUM\nHappy New Year :v"

# List of items to give players when they vote. Format: ID:Damage:Amount
Items:
  - "264:0:5"
  - "265:0:3"
  - "364:0:5"

# List of commands to execute when a player votes.
Commands:
  - "particle portal {X} {Y1} {Z} 2 2 2 10000"
  - "solomotooto {USERNAME} 15"
  - "giverbcoin {USERNAME} 20"
  - "givemoney {USERNAME} 200000"
  - "key vote {USERNAME} 1"
  - "key premium {USERNAME} 1"
