---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: true
  message: "§6§l【§bSKY§aBLOCK §eMINETOWN §c1.13x§f->§a1.14x§6】"
OutdatedClient:
  custom: true
  message: "§cPhiên bản MCPE của bạn không thể vào được Server!"
OutdatedServer:
  custom: true
  message: "§cRất tiếc! Máy chủ lỗi thời!"
WhitelistedServer:
  custom: true
  message: "§cServer Chưa Mở!"
FullServer:
  custom: true
  message: "&e{PLAYER}&b, The Server is full &c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dTry to join later :)"
FirstJoin:
  enable: true
  message: "§bThank! §a{PLAYER}§e Vào Server Lần Đầu Tiên :D."
Join:
  hide: false
  custom: true
  message: "§a§lBạn §f{PLAYER}§b Đã Vào Server!!!"
Quit:
  hide: false
  custom: true
  message: "§e§lBạn §f{PLAYER}§e Đã Out Vì Sợ Mẹ Gank =))"
WorldChange:
  enable: true
  message: "§eBạn §a{PLAYER}§e Đã Phóng Từ §6{ORIGIN}§e Qua &6{TARGET}"
Death:
  hide: true
  custom: true
  message: "§e{PLAYER} Ngủm :<"
  death-contact-message:
    hide: false
    custom: true
    message: "§cOh! {PLAYER} Đã bị giết bởi {BLOCK} =))"
  kill-message:
    hide: false
    custom: true
    message: "§9{PLAYER} §eĐã bị giết bởi §c{KILLER} §fBằng {WEAPON}"
  death-projectile-message:
    hide: false
    custom: true
    message: "§c§l{PLAYER} Đã bị bắn chết bởi §a{KILLER} §fBằng {WEAPON}"
  death-suffocation-message:
    hide: false
    custom: true
    message: "§b{PLAYER} chết ngạt"
  death-fall-message:
    hide: false
    custom: true
    message: "§c{PLAYER} té lầu!"
  death-fire-message:
    hide: false
    custom: true
    message: "§c{PLAYER} bị cháy"
  death-on-fire-message:
    hide: false
    custom: true
    message: "§c{PLAYER} bị đốt cháy"
  death-lava-message:
    hide: false
    custom: true
    message: "§9{PLAYER} tập bơi trong Lava"
  death-drowning-message:
    hide: false
    custom: true
    message: "§b{PLAYER} chết đuối, vì không biết bơi =))"
  death-explosion-message:
    hide: false
    custom: true
    message: "§c{PLAYER} tự hủy"
  death-void-message:
    hide: false
    custom: true
    message: "§c{PLAYER} rơi vào khoảng trống"
  death-suicide-message:
    hide: false
    custom: true
    message: "§c{PLAYER} tự sát"
  death-magic-message:
    hide: false
    custom: true
    message: "§c{PLAYER} đã bị giết bởi một câu thần chú"
...
